### ISSUE TITLE
Import predictors and phenotype instances

### ISSUE THREAD

**Issue by prismofeverything** [bmeg/protograph#2]
These are living in kafka topics right now, they need to be converted by protograph and imported into the BMEG. The current topics to import now are:

* gdsc.scan.bmeg.GeneExpression
* gdsc.scan.bmeg.ResponseCurve
* gdsc.scan.ga4gh.Biosample
* ncbi.Pubmed
* ucsc.bmeg.LinearSignature
* ucsc.bmeg.Predictor
* ucsc.bmeg.PredictorAssociation

**Comment by kellrott** [comment]
Looks good
